### ISSUE TITLE
Why do I fix the seed and the results are still different？

### ISSUE THREAD

**Issue by daidaiershidi** [cotton-ahn/HASR_iccv2021#1]
Note that evaluation results can be a bit different from the ones from our paper since the video representation encoder works in a sampling-based way.

I don't understand the meaning of this sentence. Why do I fix the seed and the results are still different？

```
seed = 0
random.seed(seed)
np.random.seed(seed)
os.environ['PYTHONHASHSEED'] = str(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.backends.cudnn.deterministic=True
# torch.backends.cudnn.benchmark = True
```

**Comment by cotton-ahn** [comment]
The given code is based on the seed=0, but sometimes we conducted the experiments with different seeds. Unfortunately we did not record the exact seed number, but we found out that the result does not change too much compared to the original ones.
